### ISSUE TITLE
Newer version available 

### ISSUE THREAD

**Issue by bedroesb** [AustralianBioCommons/human-omics-data-sharing-field-guide#3]
Hello @mshadbolt 
I wanted to let you know that there is a newer version available, 1.23.0, this adds a `Built by ETT` notion in the footer and is part of the new branding we are going for. You are of course free to to not update ;) Multiple new improvements are made as seen in the changelog:https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/releases

https://github.com/AustralianBioCommons/human-omics-data-sharing-field-guide/blob/3403baf8830e1902e0bb037e76a8ae5eab30e838/Gemfile#L7

If you have questions of any kind about the theme, please do so!

**Comment by mshadbolt** [comment]
Thanks for letting me know @bedroesb ! I will try it out :-)

**Comment by mshadbolt** [comment]
successfully upgraded! 

https://github.com/AustralianBioCommons/human-omics-data-sharing-field-guide/blob/d753fcdb62b4d63698a5c2bc764b9cdedaff7e76/Gemfile#L7
